name: deploy-container

on:
  push:
    branches: [master]
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH  # Правильно обновляем $PATH для всех шагов
          pnpm install
        env:
          SHELL: /bin/bash

      - name: Build
        run: |
          pnpm build

      - uses: shinyinc/action-aws-cli@v1.2

      - name: AWS
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
